Dockerfile
Add docker file for serve static site
Step to test:
1. Build docker image
```
docker build -t app .
```
2. Run docker imade
```
docker run --rm -it -p 8080:80 app
```
3. Webpage should be display on http://localhost:8080
Resolve: #2
=> feat: add dockerfile for serve static site

README.md
=> feat: update README.me

src/app/component/mdl-add-wallet/mdl-add-wallet.component.html, src/app/component/mdl-add-wallet/mdl-add-wallet.component.scss, src/app/component/mdl-add-wallet/mdl-add-wallet.component.ts
add wallet to modal
Resolve: #7
=> add wallet to modal

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts, src/app/page/setting/setting.component.ts
=> fixes navbar when change cookie

src/app/page/setting/setting.component.html
reduct icon size of edit profile name in setting page
Resolve: #23
=> feat: reduct icon size of edit profile name in setting page

src/app/layouts/footer/footer.component.html, src/app/layouts/footer/footer.component.scss
Implement layout of footer following below.
Resolve: #12
=> feat: layout of footer

angular.json, package-lock.json, package.json, src/app/component/mdl-add-wallet/mdl-add-wallet.component.ts, src/app/service/flux.service.ts, src/assets/js/custom.js, src/assets/js/jsonpath-0.8.0.js
Resolve: #36 
call api node list
filter node from wallet
add node to cookie
=> add node to cookie

src/app/page/setting/setting.component.html
Set auto focus input name when user click edit profile name.
Resolve: #40
=> feat: auto focus input name when user click edit profile name

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts
=> feat: add new profile

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts
=> switch profile

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts
Protect add new duplicate profile name.
Resolve: #44
=> feat: protect add new duplicate profile name

src/app/layouts/navbar/navbar.component.ts
Cleanup error message
Fixed: #44
=> fix: cleanup error message

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts
User able enter for save in new user profile.
Resolve: #48, Fixed #55
=> feat: user able enter for save in new user profile

src/app/layouts/navbar/navbar.component.html
fixed: space of add new profile icon.
Resolve: #50
=> fixed: space of add new profile icon

src/app/layouts/navbar/navbar.component.html
Change color of add new profile icon.
Resolve: #46
=> feat change color of add new profile icon

src/app/page/setting/setting.component.html, src/app/page/setting/setting.component.ts
=> fixed: protect empty input edit profile name

README.md, src/app/page/setting/setting.component.html, src/app/page/setting/setting.component.scss, src/app/page/setting/setting.component.ts
Resolve: #69 
remove profile from setting page
=> Managewallet

src/app/service/flux.service.ts
=> fixes bug fetch node

src/app/layouts/navbar/navbar.component.html, src/app/layouts/navbar/navbar.component.ts
=> feat: add active select profile

src/app/layouts/footer/footer.component.html
=> add bug report to footer
